const SUBJECTS = [
  { kod: '1103/3', nama: 'BAHASA MELAYU 3 (UBBM)' },
  { kod: '1119/3', nama: 'BAHASA INGGERIS 3 (UBBI)' },
  { kod: '4531/3', nama: 'FIZIK 3 (UAS)' },
  { kod: '4541/3', nama: 'KIMIA 3 (UAS)' },
  { kod: '4551/3', nama: 'BIOLOGI 3 (UAS)' },
  { kod: '1103/4 & 1119/4', nama: 'UJIAN MENDENGAR (BM & BI)' },
  { kod: '1103/1', nama: 'BAHASA MELAYU 1' },
  { kod: '2611/1', nama: 'PENDIDIKAN SENI VISUAL 1' },
  { kod: '1103/2', nama: 'BAHASA MELAYU 2' },
  { kod: '1119/1', nama: 'BAHASA INGGERIS 1' },
  { kod: '1119/2', nama: 'BAHASA INGGERIS 2' },
  { kod: '5226', nama: 'TASAWWUR ISLAM' },
  { kod: '1249/1', nama: 'SEJARAH 1' },
  { kod: '1249/2', nama: 'SEJARAH 2' },
  { kod: '1449/1', nama: 'MATEMATIK 1' },
  { kod: '1449/2', nama: 'MATEMATIK 2' },
  { kod: '5402/1', nama: 'AL-SYARIAH 1' },
  { kod: '1223/1', nama: 'PENDIDIKAN ISLAM 1' },
  { kod: '1225', nama: 'PENDIDIKAN MORAL' },
  { kod: '5228', nama: 'PENDIDIKAN SYARI’AH ISLAMIAH 1' },
  { kod: '5302/2', nama: 'MAHARAT AL-QURAN 2' },
  { kod: '5404/1', nama: 'MANAHIJ AL-‘ULUM AL-ISLAMIAH 1' },
  { kod: '2611/2', nama: 'PENDIDIKAN SENI VISUAL 2' },
  { kod: '3763/1', nama: 'REKA CIPTA 1' },
  { kod: '1511/1', nama: 'SAINS 1' },
  { kod: '4531/1', nama: 'FIZIK 1' },
  { kod: '1511/2', nama: 'SAINS 2' },
  { kod: '4531/2', nama: 'FIZIK 2' },
  { kod: '3769/1', nama: 'SAINS RUMAH TANGGA 1' },
  { kod: '4541/1', nama: 'KIMIA 1' },
  { kod: '4541/2', nama: 'KIMIA 2' },
  { kod: '9216', nama: 'KESUSASTERAAN CINA' },
  { kod: '9217', nama: 'KESUSASTERAAN TAMIL' },
  { kod: '2280/1', nama: 'GEOGRAFI 1' },
  { kod: '2280/2', nama: 'GEOGRAFI 2' },
  { kod: '3766/1', nama: 'PERNIAGAAN 1' },
  { kod: '4551/1', nama: 'BIOLOGI 1' },
  { kod: '3766/2', nama: 'PERNIAGAAN 2' },
  { kod: '4551/2', nama: 'BIOLOGI 2' },
  { kod: '3472/1', nama: 'MATEMATIK TAMBAHAN 1' },
  { kod: '3472/2', nama: 'MATEMATIK TAMBAHAN 2' },
  { kod: '4572/1', nama: 'SAINS SUKAN 1' },
  { kod: '5401/1', nama: 'USUL AL-DIN 1' },
  { kod: '4572/2', nama: 'SAINS SUKAN 2' },
  { kod: '3768/1', nama: 'ASAS KELESTARIAN 1' },
  { kod: '3756/1', nama: 'PRINSIP PERAKAUNAN 1' },
  { kod: '3756/2', nama: 'PRINSIP PERAKAUNAN 2' },
  { kod: '5405/1', nama: 'AL-ADAB WAL AL-BALAGHAH' },
  { kod: '5227/1', nama: 'PENDIDIKAN AL-QURAN DAN AL-SUNNAH 1' },
  { kod: '5303/1', nama: 'TURATH AL-QURAN DAN AL-SUNNAH 1' },
  { kod: '3770/1', nama: 'SAINS KOMPUTER 1' },
  { kod: '3767/1', nama: 'EKONOMI 1' },
  { kod: '3767/2', nama: 'EKONOMI 2' },
  { kod: '7203/1', nama: 'PEMPROSESAN MAKANAN' },
  { kod: '7407/1', nama: 'REKA BENTUK GRAFIK DIGITAL 1' },
  { kod: '3771/1', nama: 'GRAFIK KOMUNIKASI TEKNIKAL 1' },
  { kod: '6351/1', nama: 'BAHASA CINA 1' },
  { kod: '6351/1-TAMIL', nama: 'BAHASA TAMIL 1' },
  { kod: '6351/2', nama: 'BAHASA CINA 2' },
  { kod: '6351/2-TAMIL', nama: 'BAHASA TAMIL 2' }
];

const CENTERS = [
  { kod: 'JH001', nama: 'SMK JEMENTAH' },
  { kod: 'JH005', nama: 'SMK CANOSSIAN CONVENT' },
  { kod: 'JH009', nama: 'SMK TINGGI SEGAMAT' },
  { kod: 'JH013', nama: 'SMK SEG HWA' },
  { kod: 'JH014', nama: 'SMJK SEG HWA' },
  { kod: 'JH017', nama: 'SMK BULUH KASAP' },
  { kod: 'JH021', nama: 'SMK DATO AHMAD ARSHAD' },
  { kod: 'JH025', nama: 'SMK DATO BENTARA DALAM' },
  { kod: 'JH029', nama: 'SMK PADUKA TUAN' },
  { kod: 'JH033', nama: 'SMK AGAMA' },
  { kod: 'JH037', nama: 'SMK MUNSHI IBRAHIM' },
  { kod: 'JH041', nama: 'SMK CHAAH' },
  { kod: 'JH045', nama: 'SMK BEKOK' },
  { kod: 'JH049', nama: 'SMK LABIS' },
  { kod: 'JH053', nama: 'SMK TENANG STESEN' },
  { kod: 'JH057', nama: 'SMK SERI JEMENTAH' },
  { kod: 'JH061', nama: 'SMK PALONG TIMUR' },
  { kod: 'JH065', nama: 'SMK PEMANIS' },
  { kod: 'JH069', nama: 'SMK MAOKIL' },
  { kod: 'JH077', nama: 'SMK GEMEREH' },
  { kod: 'JH081', nama: 'SMK KAMARUL ARIFFIN' },
  { kod: 'JH085', nama: 'SMK BANDAR PUTRA' },
  { kod: 'JH089', nama: 'SMK SERI KENANGAN' },
  { kod: 'JH093', nama: 'SMK SERI BALI' },
  { kod: 'JH098', nama: 'SMA AL-KHAIRIAH' },
  { kod: 'JH801', nama: 'KOLEJ VOKASIONAL' },
  { kod: 'JH101', nama: 'SM SAINS SEGAMAT' },
  { kod: 'HJH001', nama: 'HOSPITAL' }
];

const SUPERVISORS = [
  'IDRIS BIN KAMIS',
  'FAIRUSSHAMIZAR BIN BONGSU',
  'SHAHRIL AZMAN BIN YAKUP',
  'RAZHAN BIN JAINUDDIN',
  'MUHAMMAD FAUZI BIN MASROM',
  'MOHAMAD BIN HASHIM',
  'MOHD NIZAM BIN SUBANI',
  'KARTHIK A/L SELVA KUMARAN',
  'MOHD MAZRAN BIN ISMAIL',
  'MOHD SAMSULNAHAR BIN MOHD YUSOF'
];
